language: go
arch:
    - amd64
    - ppc64le

go:
  - "1.13.x"
  - tip

go_import_path: go4.org

before_install:
  - go mod tidy
  - git diff --exit-code go.mod
  - git diff --exit-code go.sum
  - go mod download
